services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Auto-install Jenkins without setup wizard

  postgres:
    image: postgres:14.17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: jirapass
      POSTGRES_DB: jiradb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jira:
    image: atlassian/jira-software:9.4.0
    container_name: jira
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/jiradb
      ATL_JDBC_USER: jira
      ATL_JDBC_PASSWORD: jirapass
      JVM_MINIMUM_MEMORY: 1024m
      JVM_MAXIMUM_MEMORY: 2048m
    volumes:
      - jira_home:/var/atlassian/application-data/jira

volumes:
  jenkins_home:
  postgres_data:
  jira_home:
